Repository Visssarion/Memory-Card-Game, pull requests merged in 2023-11, with the labels that each got.

#12 Card flip
  cards/sprites/CardBack.png
  cards/sprites/CardBack.png.import
  scenes/objects/card.tscn
  scripts/classes/card.gd
Labels: feature

#16 ADD: Dynamic Core script for the board
  notes/objects/card.tscn
  notes/scenes/test_dev.tscn
  project.godot
  scripts/classes/card.gd
  scripts/core/game.gd
Labels: feature

#20 Feature/matching
  .github/CODEOWNERS
  .github/Docs/Flowchartzzz.PNG
  cards/resources/Themes/FiftySpaceHorror/1.tres
  cards/resources/Themes/FiftySpaceHorror/10.tres
  cards/resources/Themes/FiftySpaceHorror/2.tres
  cards/resources/Themes/FiftySpaceHorror/3.tres
  cards/resources/Themes/FiftySpaceHorror/4.tres
  cards/resources/Themes/FiftySpaceHorror/5.tres
  cards/resources/Themes/FiftySpaceHorror/6.tres
  cards/resources/Themes/FiftySpaceHorror/7.tres
  cards/resources/Themes/FiftySpaceHorror/8.tres
  cards/resources/Themes/FiftySpaceHorror/9.tres
  cards/sprites/Themes/FiftySpaceHorror/1.png
  cards/sprites/Themes/FiftySpaceHorror/1.png.import
  cards/sprites/Themes/FiftySpaceHorror/10.png
  cards/sprites/Themes/FiftySpaceHorror/10.png.import
  cards/sprites/Themes/FiftySpaceHorror/2.png
  cards/sprites/Themes/FiftySpaceHorror/2.png.import
  cards/sprites/Themes/FiftySpaceHorror/3.png
  cards/sprites/Themes/FiftySpaceHorror/3.png.import
  cards/sprites/Themes/FiftySpaceHorror/4.png
  cards/sprites/Themes/FiftySpaceHorror/4.png.import
  cards/sprites/Themes/FiftySpaceHorror/5.png
  cards/sprites/Themes/FiftySpaceHorror/5.png.import
  cards/sprites/Themes/FiftySpaceHorror/6.png
  cards/sprites/Themes/FiftySpaceHorror/6.png.import
  cards/sprites/Themes/FiftySpaceHorror/7.png
  cards/sprites/Themes/FiftySpaceHorror/7.png.import
  cards/sprites/Themes/FiftySpaceHorror/8.png
  cards/sprites/Themes/FiftySpaceHorror/8.png.import
  cards/sprites/Themes/FiftySpaceHorror/9.png
  cards/sprites/Themes/FiftySpaceHorror/9.png.import
  cards/sprites/Themes/FiftySpaceHorror/BACK.png
  cards/sprites/Themes/FiftySpaceHorror/BACK.png.import
  nodes/objects/card.tscn
  nodes/objects/game_camera_2d.tscn
  nodes/scenes/test_dev.tscn
  notes/scenes/test_dev.tscn
  project.godot
  scripts/classes/card.gd
  scripts/classes/card_data.gd
  scripts/classes/game_camera_2d.gd
  scripts/core/game.gd
Labels: bug, enhancement, feature

#22 ADD: Card deck
  nodes/scenes/test_dev.tscn
  scripts/classes/deck.gd
  scripts/core/game.gd
Labels: enhancement, feature

#28 Added card highlighting animation [Juice]
  nodes/objects/card.tscn
  scripts/classes/card.gd
  shaders/card.gdshader
  shaders/card_material.tres
Labels: enhancement

#31 Changed setttings to be a resource.
  nodes/scenes/Levels/level_1.tscn
  nodes/scenes/Levels/level_2.tscn
  nodes/scenes/Levels/level_3.tscn
  nodes/scenes/Levels/level_4.tscn
  nodes/scenes/Levels/level_5.tscn
  scripts/classes/settings.gd
  scripts/core/game.gd
Labels: enhancement
